### ISSUE TITLE
Checkpoint model cannot be used for inference

### ISSUE THREAD

**Issue by erip** [monologg/KoBERT-NER#2]
Because the `model/config.json`'s `label2id` and `id2label` do not contain the NER labels from `data/labels.txt`, the model cannot be used for inference.

I haven't tried manually updating the JSON to  include the labels yet, but do you think that would be a possible fix or would the training code need to be changed?

**Comment by monologg** [comment]
As I know, `label2id` and `id2label` in config.json is not required for inference, when you run `python3 main.py --do_eval --write_pred`

Unfortanately, at the period when I made this code, `label2id` or `id2label` were not in `config.json`.  (It was appeared from quiet recent version of `transformers` library)

This code wasn't planned to be work solely with checkpoint, but running with code together (`python3 main.py --do_eval --write_pred`)
-----
> I haven't tried manually updating the JSON to include the labels yet, but do you think that would be a possible fix or would the training code need to be changed?

**I'm not 100% sure**, but by manually changing the JSON, result will be shown.

But there will be another problem. This NER is `word-level` tagging, but `BERT` is `token-level` tagging. It means that word could be consisted of more than 2 tokens. 

You might know that in original BERT paper, if the word is consisted of more than 2 tokens, it tags the word with first token, ignoring the rest of the token. 

You can find this part on ` convert_examples_to_features` in `data_loader.py`. I recommend you to see that function.

**Comment by monologg** [comment]
By the way, this code wasn't planned for inferencing new texts, like you did on issue #1 

This code was for just checking the performance of `kobert` and `distilkobert`

**Comment by monologg** [comment]
@erip 

I'll close this issue. If you have any additional issues, feel free to raise new issue:)
