### ISSUE TITLE
--write_pred 옵션 설명

### ISSUE THREAD

**Issue by gyunggyung** [monologg/KoBERT-NER#3]
안녕하세요! 모델을 학습하다가 `--write_pred` 옵션 즉, predictable 을 하는 방법을 조금 더 상세히 설명해주셨으면 합니다. 

1. 원하는 문장을 input으로 넣었을 때, 해당하는 감정을 output으로 내는 코드는 어떻게 작성할까요?
2. 학습 후,  predictable 을 하는 데이터셋은 어디에 넣어야 될까요?

감사합니다.

**Comment by monologg** [comment]
> 안녕하세요! 모델을 학습하다가 `--write_pred` 옵션 즉, predictable 을 하는 방법을 조금 더 상세히 설명해주셨으면 합니다.
> 
> 1. 원하는 문장을 input으로 넣었을 때, 해당하는 감정을 output으로 내는 코드는 어떻게 작성할까요?
> 2. 학습 후,  predictable 을 하는 데이터셋은 어디에 넣어야 될까요?
> 
> 감사합니다.

- `--write_pred`는 **evaluation set에 대해서 예측 결과를 뱉는 부분**입니다. 해당 레포는 성능 지표 측정만을 위해서 만들어서 새로운 input에 대한 prediction은 코드 작성시 고려하지 않았습니다.
- 해당 부분에 대해서는 코드를 직접 짜셔야 할 것 같습니다. 
- 참고로 해당 레포는 감정분석이 아닌 NER입니다. 감정분석과 관련된 레포는 [KoBERT-nsmc](https://github.com/monologg/KoBERT-nsmc)를 참고하시면 될 것 같습니다.

**Comment by gyunggyung** [comment]
KoBERT-nsmc 코드 또한 prediction은 따로 작성해야 될까요?

감사합니다.

**Comment by monologg** [comment]
> KoBERT-nsmc 코드 또한 prediction은 따로 작성해야 될까요?
> 
> 감사합니다.

KoBERT-nsmc도 그렇게 해야할 것 같습니다ㅠ

참고로 `data_loader.py`의 `convert_examples_to_features`를 참고하여 raw_text를 input_ids, attention_mask, token_type_ids로 만드는 함수 작성후, 저장된 모델을 로드하여 forward하시면 될 것 같습니다.

추후에 prediction 관련해서 코드 추가하도록 하겠습니다:)

감사합니다.

**Comment by gyunggyung** [comment]
답변 감사합니다 :)
ᐧ

**Comment by monologg** [comment]
@gyunggyung 

안녕하세요

KoBERT-nsmc에 prediction 관련 파일 추가하였습니다.

[https://github.com/monologg/KoBERT-nsmc#prediction](https://github.com/monologg/KoBERT-nsmc#prediction) 참고하시면 될 것 같습니다:)
